### ISSUE TITLE
请问为什么跑完main_test_srmd.py在result文件夹里面的图片尺寸和testsets里面一样大呢？（小白

### ISSUE THREAD

**Issue by WK-Luo** [HollowMan6/SRMD-Pytorch#1]

**Comment by HollowMan6** [comment]
因为testset此仓库只提供了高质量的图片，所以在验证的时候是会对testset中图片进行一个程序性的模拟退化处理:

https://github.com/HollowMan6/SRMD-Pytorch/blob/main/main_test_srmd.py#L154-L159
将其下采样缩小指定的倍数分辨率与其他增加噪声处理之后输入模型，进行超分辨率，这样好与高质量图片进行比较，自然生成的图片就和测试集中提供的高质量图片一样的分辨率大小了。

**Comment by WK-Luo** [comment]
原来如此，谢谢。
